{% set name = "tibanna" %}
{% set version = "0.18.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d4f0cde490e7fe6269ee08ff966293af60af1ef27dd8616ba29856b58fed0907

build:
  number: 0
  entry_points:
    - tibanna = tibanna.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - benchmark-4dn >=0.5.8
    - boto3 >=1.9.0
    - botocore >=1.12.1
    - pip
    - python ==3.6
    - python-lambda-4dn ==0.12.3
    - requests >=2.22.0
    - urllib3 >=1.24
  run:
    - benchmark-4dn >=0.5.8
    - boto3 >=1.9.0
    - botocore >=1.12.1
    - python ==3.6
    - python-lambda-4dn ==0.12.3
    - requests >=2.22.0
    - urllib3 >=1.24

test:
  imports:
    - tibanna

about:
  home: "http://data.4dnucleome.org"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "Tibanna runs portable pipelines (in CWL/WDL) on the AWS Cloud."
  doc_url: "https://tibanna.readthedocs.io/en/latest/"

extra:
  recipe-maintainers:
    - soolee
