{% set name = "tibanna" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b509f02793a9ed1ead987b0dc9f55e594eddfa3576312da81192de0baceac3b

build:
  number: 0
  noarch: python
  entry_points:
    - tibanna = tibanna.__main__:main
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - benchmark-4dn >=0.5.8
    - boto3 >=1.9.0
    - botocore >=1.12.1
    - pip
    - python >=3.6
    - python-lambda-4dn ==0.12.3
    - requests >=2.22.0
    - urllib3 >=1.24
  run:
    - benchmark-4dn >=0.5.8
    - boto3 >=1.9.0
    - botocore >=1.12.1
    - python >=3.6
    - python-lambda-4dn ==0.12.3
    - requests >=2.22.0
    - urllib3 >=1.24

test:
  imports:
    - tibanna

about:
  home: http://data.4dnucleome.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Tibanna runs portable pipelines on the AWS Cloud.
  doc_url: https://tibanna.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - soolee
